language: ruby
cache: bundler

# script: bundle exec rake test TESTOPTS=-v

# http://rubies.travis-ci.org/
# See here for osx_image -> OSX versions: https://docs.travis-ci.com/user/languages/objective-c
matrix:
  include:
    - rvm: 2.7.0
      os: linux

branches:
  only:
    - master

sudo: false
dist: trusty # for TLSv1.2 support

addons:
  apt:
    packages:
      - libgmp3-dev
